### PR TITLE
bugfix/macos-ci-failure

### LINKED ISSUE #10: CI failing for MacOS
Current tests are failing for all MacOS options (3.9,3.10,3.11) - seems some extension is recommended??

### PR DESCRIPTION
**Pull request by BrianWhitneyAI**
### Description

Resolves #10

### CODE REVIEW

**Review by toloudis — APPROVED** [review]
Awesome if this fixes it - should imageio (or bioio-imageio?) automatically install ffmpeg or is it a known thing that users have to install it themselves?

**Review by toloudis — APPROVED** [review]

**Comment by BrianWhitneyAI** [comment]
> Awesome if this fixes it - should imageio (or bioio-imageio?) automatically install ffmpeg or is it a known thing that users have to install it themselves?

The direct error that users see is `RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.` I am ok with passing this to users instead of trying to do it for them since there is some difference between OS. So I think that imageio has already made a decision here. I think I slightly lean towards bioio-imageio reflecting imageios choice

**Review by evamaxfield — APPROVED** [review]
Ahhh this makes sense. I think we should add a warning or raise an exception that explains the missing FFMPEG library

**Review by SeanLeRoy — APPROVED** [review]

**Comment by BrianWhitneyAI** [comment]
@evamaxfield  I think the raised error is already fairly descriptive `RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.` Im going to merge this for now. Feel free to open a new issue if you think it needs more.

**Comment by evamaxfield** [comment]
> @evamaxfield I think the raised error is already fairly descriptive `RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.` Im going to merge this for now. Feel free to open a new issue if you think it needs more.

Ahhhh understood. Totally agree, misread prior messages.

**Pull request merged**
